### PR TITLE
modulesync 1.1.0

### PR DESCRIPTION
**Pull request by wyardley**

### CODE REVIEW

**Comment by wyardley** [comment]
So the issue is:
`    require     => Service[$service_name],`
(i.e., `    require     => Service['jenkins'],`
however, the service isn't defined here.

Presumably, this would be to notify a service setup by the Jenkins module, but that's not a dependency or in fixtures, so I guess either we should get rid of the require, or require the Jenkins module?

**Comment by bastelfreak** [comment]
@wyardley IMO we should get rid of it. this ordering should be done in a profile.

**Comment by ekohl** [comment]
@wyardley I think it should use ```$::jenkins_job_builder::service``` in ```$::jenkins_job_builder::job```. Then ```$::jenkins_job_builder``` should also use ```params``` since it's defined there too. Then you can consider allowing it to be ```undef``` but in this case I think defaulting to ```jenkins``` isn't that base. Just add a ```pre_condition``` that defines it.

**Comment by wyardley** [comment]
@ekohl thanks for the suggestions, this hasn't been a high priority, but I think your suggestion is a reasonable way to approach it. Let me know how the most recent commit looks.

**Pull request merged**
