### PR TITLE
CentOS 7 Fix

### PR DESCRIPTION
**Pull request by thanandorn**
Fixes for installation on CentOS 7 and `exec { manage jenkins job` binary path.

Cheers,
Tron

### CODE REVIEW

**Comment by madAndroid** [comment]
LGTM :+1: 
Could you please look at squashing your commits (just the ones that have been reverted) ?
These changes also coincide with #20 - it may be worth consolidating effort around some of the changes with @gregswift

**Comment by thanandorn** [comment]
@madAndroid 

I'm trying to squash the commits. Hope to get it right soon.

Thanks,
Tron

**Comment by madAndroid** [comment]
AFAICT, these tests are failing due to inconsistent hash ordering in ruby 1.8 ... not much we can do to get around that, unfortunately :-/ In these instances, I've often pushed another commit with a small change, prompting the test rebuild, but there's no guarantee the tests will pass next time around.

**Comment by madAndroid** [comment]
Closing in favour of #20

**Pull request closed without merging**
