### PR TITLE
Prep for release 2.0.0

### PR DESCRIPTION
**Pull request by mkrakowitzer**

### CODE REVIEW

**Comment by madAndroid** [comment]
Looks like the failure is down to a trailing comma in the spec hash .. working on a fix, will send a PR asap

**Comment by madAndroid** [comment]
Test failures addressed in #24

**Comment by juniorsysadmin** [comment]
A major version bump is a good time to drop Ruby 1.8 support, perform a modulesync and get this module into a bit more manageable state. Thoughts?

**Comment by madAndroid** [comment]
Sounds good to me 👍 - I've had issues with the tests after module-sync's been applied though, due to differences in the `.to_yaml` implementation in ruby 1.9 and 2.x - as detailed in #34 

No idea how to work around that - any ideas @bastelfreak / @juniorsysadmin / @mkrakowitzer / @alexharv074 ?

**Comment by bastelfreak** [comment]
ugh this is so old :(
we should discuss the modulesync in the PR #34 and directly spin up another as because there were a lot of changes in modulesync in the last days.

**Comment by madAndroid** [comment]
@bastelfreak - yeah, this module's needed some attention for a while :-/ thanks for taking a look :)
I think this PR can be closed in favour of #34 - and as you said, would be good to do another module sync directly after. I'm not very familiar with the process (only done it once so far!) - but I'll give it a go once #34 has been merged in - looks like the tests are passing now :D

**Comment by madAndroid** [comment]
Hmm.. just realised this PR is still valid - and only contains CHANGELOG and versioning changes - probably worth keeping open until after another module sync has been done.

**Comment by bastelfreak** [comment]
yep I would keep this one open and merge after the modulesync

**Comment by bastelfreak** [comment]
@madAndroid for modulesync:
* clone our modulesync_config thing
* bundle install --path .vendor/ 
* bundle exec msync update -f jenkins --message "modulesync 0.7.0"

**Comment by madAndroid** [comment]
@bastelfreak - awesome, cheers for that :)

**Comment by madAndroid** [comment]
Closing in favour of #36

**Pull request closed without merging**
