### PR TITLE
Apply modulesync to module

### PR DESCRIPTION
**Pull request by madAndroid**
- Sync up changes using modulesync

### CODE REVIEW

**Comment by bastelfreak** [comment]
I did some yak shaving. Can somebody else take a look at the rspec stuff here?

**Comment by madAndroid** [comment]
@bastelfreak - thanks for the yak shaving! I've sorted out the syntax errors, but still seeing some failures .. looking into those atm

**Comment by madAndroid** [comment]
Current failures appear to be the difference between how ruby 1.9 vs 2.x handles `.to_yaml` method - each generates valid YAML, it's just the way the indentation is handled. I'm not quite sure how we deal with this differences at the rspec level

**Comment by madAndroid** [comment]
hmm.. actually, it looks as though 1.9 and 2.1 behave the same way in puppet 3 - it's in puppet 4 that the difference comes out

**Comment by bastelfreak** [comment]
Hi @madAndroid, do you have some idead about the issues on travis?

**Comment by madAndroid** [comment]
@bastelfreak - I do indeed: it's because of the difference in the implementation of `to_yaml` between a combination of ruby 1.9 and puppet 3, and ruby 2.x / puppet 4 - not 100% sure, but I think it's down to that - the YAML is being created differently between those combinations - in earlier versions, `to_yaml` creates different indentation to how they're created in later versions.

A possible solution to this would be to use `to_yaml` itself within the specs, instead of explicitly setting the indentation and YAML structure - I'll have a go at that approach, and see if it fixes the tests.

**Comment by bastelfreak** [comment]
ah sounds good!

**Comment by madAndroid** [comment]
@bastelfreak - tests pass now :)

**Pull request merged**
